{"name": "test_demo2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 != 2", "trace": "self = <TestCase.test_pytest2.Test_py object at 0x033422F0>\n\n    def test_demo2(self):\n        a = 2\n        b = 2\n>       assert  a != b\nE       assert 2 != 2\n\nTestCase\\test_pytest2.py:10: AssertionError"}, "attachments": [{"name": "log", "source": "5e8ec5b3-d1b9-41a4-8b39-a7235c66c942-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "b81fa03d-4ed8-4ae8-a066-9063a893b79a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a9c19077-6ace-43b2-821c-bb180b6c94ae-attachment.txt", "type": "text/plain"}], "start": 1556008964345, "stop": 1556008964345, "uuid": "1cde627e-8fc3-4a8f-805d-04b754b9b196", "historyId": "081112ed66dcafb9c02e7ad816b4b7ca", "fullName": "TestCase.test_pytest2.Test_py#test_demo2", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_pytest2"}, {"name": "subSuite", "value": "Test_py"}, {"name": "host", "value": "WH-201901171602"}, {"name": "thread", "value": "8972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_pytest2"}]}