{"name": "test_demo2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 != 1", "trace": "self = <TestCase.test_pytest.Test_py object at 0x0332F5F0>\n\n    def test_demo2(self):\n        a = 1\n        b = 1\n>       assert  a != b\nE       assert 1 != 1\n\nTestCase\\test_pytest.py:10: AssertionError"}, "attachments": [{"name": "log", "source": "1b7a1649-f064-44b6-8287-a155448a703b-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "fcc1e60a-a669-4cb4-90dc-798da9a37827-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f2376ca8-7d5f-4817-8a02-0a038a727bc8-attachment.txt", "type": "text/plain"}], "start": 1556008964278, "stop": 1556008964278, "uuid": "6c2f5c17-47fc-45b7-a346-a5dd06a3bc3c", "historyId": "5054a7148a22105f56412c94ad5120f2", "fullName": "TestCase.test_pytest.Test_py#test_demo2", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "Test_py"}, {"name": "host", "value": "WH-201901171602"}, {"name": "thread", "value": "8972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_pytest"}]}